### ISSUE TITLE
gprconfig?

### ISSUE THREAD

**Issue by robdaemon** [gabriele-galeotti/SweetAda#4]
Is it possible to use the SweetAda toolchains with gprconfig / gprbuild?

I've been wanting a good AArch64 Ada toolchain for some time - and this looks like it could work great.

It looks like gprconfig (at least installed on Debian unstable) doesn't understand it:

```
rroland@booker:~$ gprconfig --target=aarch64-sweetada-elf
No compilers found for target aarch64-sweetada-elf
```

**Comment by gabriele-galeotti** [comment]
Hi.

Firstly, you have to make the toolchain visible in path. If the toolchain
is installed
in the default location (/opt/sweetada), then:

***@***.***:~# PATH=/opt/sweetada/bin:$PATH gprconfig
--target=aarch64-sweetada-elf
--------------------------------------------------
gprconfig has found the following compilers on your PATH.
Only those matching the target and the selected compilers are displayed.
  1. GCC-ASM for Asm in /opt/sweetada/bin/ version 11.3.0
  2. GCC-ASM for Asm2 in /opt/sweetada/bin/ version 11.3.0
  3. GCC-ASM for Asm_Cpp in /opt/sweetada/bin/ version 11.3.0
  4. LD for Bin_Img in /opt/sweetada/bin/ version 2.38
  5. GCC for C in /opt/sweetada/bin/ version 11.3.0
Select or unselect the following compiler (or "s" to save):

Tha Ada compiler is not detected though.

Unfortunately gprbuild supports only toolchains in its database by default.
gprconfig is dependent on that, and so could not find the compiler. In
order to allow
gprconfig detecting the compiler, heavy patches are needed I guess.

Being said that, the SweetAda build system creates a gprbuild project file
that
is used for compiling, but it does not cover every aspect of the toolchain
(e.g., linker
specifications).

I'll try to investigate on that, but don't hold your breath.

G
